services:

  cdp:
    image: cdp:latest
    container_name: cdp
    ports:
      - 5003:5003
    environment:
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_APP_API_URL=${VITE_APP_API_URL}
      - VITE_APP_DSP_URL=${VITE_APP_DSP_URL}
      - VITE_APP_GOOGLE_MAPS_API_KEY=${VITE_APP_GOOGLE_MAPS_API_KEY}
      - VITE_APP_VERSION=${VITE_APP_VERSION}
    restart: unless-stopped
