services:

  cdp:
    image: cdp:latest
    container_name: cdp
    ports:
      - 5003:5003
    environment:
      - VUE_APP_NAME=${VUE_APP_NAME}
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_DSP_URL=${VUE_APP_DSP_URL}
      - VUE_APP_GOOGLE_MAPS_API_KEY=${VUE_APP_GOOGLE_MAPS_API_KEY}
      - VUE_APP_VERSION=${VUE_APP_VERSION}
    restart: unless-stopped
