version: '3.8'

services:

  cdp:
    image: cdp
    container_name: cdp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    environment:
      - VUE_APP_HEAP_ANALYTICS_APP_ID=${VUE_APP_HEAP_ANALYTICS_APP_ID}
      - VUE_APP_GOOGLE_MAPS_API_KEY=${VUE_APP_GOOGLE_MAPS_API_KEY}
      - VUE_APP_DISCOVERY_PORTAL_URL=${VUE_APP_DISCOVERY_PORTAL_URL}
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_URL=${VUE_APP_URL}
    restart: unless-stopped
