services:
  cdp:
    image: cdp
    container_name: cdp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    environment:
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_APP_API_URL=${VITE_APP_API_URL}
      - VITE_APP_DSP_URL=${VITE_APP_DSP_URL}
      - VITE_APP_GOOGLE_MAPS_API_KEY=${VITE_APP_GOOGLE_MAPS_API_KEY}
      - VITE_APP_HEAP_ANALYTICS_APP_ID=${VITE_APP_HEAP_ANALYTICS_APP_ID}
    restart: unless-stopped
