version: '3.8'

services:

  cdp:
    image: cdp
    container_name: cdp
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 5003:5003
    restart: unless-stopped