/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Cd.about': typeof import('./components/about/cd.about.vue')['default']
    'Cd.contact': typeof import('./components/contact/cd.contact.vue')['default']
    'Cd.featuredDatasets': typeof import('./components/home/cd.featured-datasets.vue')['default']
    'Cd.footer': typeof import('./components/base/cd.footer.vue')['default']
    'Cd.home': typeof import('./components/home/cd.home.vue')['default']
    'Cd.homeSearch': typeof import('./components/home/cd.home-search.vue')['default']
    'Cd.rangeInput': typeof import('./components/search-results/cd.range-input.vue')['default']
    'Cd.search': typeof import('./components/search/cd.search.vue')['default']
    'Cd.searchMap': typeof import('./components/search-results/cd.search-map.vue')['default']
    'Cd.searchResults': typeof import('./components/search-results/cd.search-results.vue')['default']
    'Cd.spatialCoverageMap': typeof import('./components/search-results/cd.spatial-coverage-map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
