query Resources($limit: Int, $after: ObjectId) {
  geojson_checksum_normalizeds(limit: $limit, query: { title_exists: true, _id_gt: $after}, sortBy: MODIFIED_DESC) {
    _id
    id
    title
    abstract
    type
    creators {
        name
    }
    files {
        size
    }
    created
  }
}