query Search($term: String!, $limit: Float, $publishedStart: String, $publishedEnd: String) {
  fuzzy_search(input: { term: $term, limit: $limit, publishedStart: $publishedStart, publishedEnd: $publishedEnd }) {
    _id
    url
    name
    description
    creator {
      List {
        name
      }
    }
    keywords
    dateCreated
    dateModified
    license {
      text
    }
    funding { 
      name
      funder {
        name
      }
    }
    citation
    highlights {
      score
      path
      texts {
        type
        value
      }
    }
    score
	}
}