query Search(
  $term: String!, 
  $pageSize: Float,
  $pageNumber: Float,
  $publishedStart: Float,
  $publishedEnd: Float,
  $dataCoverageStart: Float,
  $dataCoverageEnd: Float,
  $creatorName: String,
  $providerName: String,
) {
  filtering_cznet(input: {
    term: $term,
    pageSize: $pageSize,
    pageNumber: $pageNumber,
    publishedStart: $publishedStart,
    publishedEnd: $publishedEnd,
    dataCoverageStart: $dataCoverageStart,
    dataCoverageEnd: $dataCoverageEnd,
    creatorName: $creatorName,
    providerName: $providerName,
   }) {
    _id
    url
    name
    description
    creator {
      List {
        name
      }
    }
    provider {
      name
    }
    keywords
    dateCreated
    dateModified
    datePublished
    temporalCoverage {
      start
      end
    }
    license {
      text
    }
    funding { 
      name
      funder {
        name
      }
    }
    citation
    highlights {
      score
      path
      texts {
        type
        value
      }
    }
    score
	}
}